In [1]:
import numpy as np 

SEARCH 

In [ ]:
s = np.array([1,2,3,2,5,6,6,8,9])
x = np.where(s==2)
x

(array([1, 3]),)

SEARCH SORTED

In [6]:
ss = np.array([1,2,3,2,5,6,6,8,9])
x1 = np.searchsorted(ss,[2,5,6])
x1

array([1, 4, 5])

SORT 

In [ ]:
s1 = np.array([5,66,25,2,5,9,6,7,22])
x2 = np.sort(s1)
x2

array([ 2,  5,  5,  6,  7,  9, 22, 25, 66])

FILTER

In [ ]:
f = np.array(['a','c','f','t'])
f1 = [True,False,True,False]
x3 = f [f1]
x3

array(['a', 'f'], dtype='<U1')